version: 2.1

commands:
  install_dependencies:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  test:
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout
      - install_dependencies

      - run: |
          yarn build
          yarn lint
          yarn format
          yarn typecheck
          yarn test

  test-e2e:
    machine:
      enabled: true
      image: circleci/classic:201710-01
      docker_layer_caching: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: .circleci/install-yarn.sh

      - run:
          name: 'Run postgres'
          command: |
            docker-compose up -d
            ./.circleci/wait-for-it.sh localhost:5432 -t 10
            sleep 10
      - run: |
          source /opt/circleci/.nvm/nvm.sh
          yarn # @todo: reuse modules from cache
          yarn build
          yarn test:e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - test-e2e
