version: 2.1

commands:
  install_dependencies:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  test:
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout
      - install_dependencies
      - run: |
        yarn build
        yarn lint
        yarn format
        yarn typecheck
        yarn test

  test-e2e:
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout
      - install_dependencies
      - run: yarn build
      - run: ./scripts/dev.sh -d
      - run: yarn test:e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build_and_test
