version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10.13.0
    working_directory: /home/circleci/app
    steps:
      - checkout

      - restore_cache:
          key: v1-dep-{{ checksum "yarn.lock" }}

      - run:
          name: Install deps
          command: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - ./node_modules
            - ~/.cache
          key: v1-dep-{{ checksum "yarn.lock" }}

      - run:
          name: Run tests
          command: yarn test

  test-e2e:
    machine:
      enabled: true
      image: circleci/classic:201710-01
      docker_layer_caching: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
      - run: .circleci/install-yarn.sh

      - run:
          name: 'Run postgres'
          command: |
            docker-compose up -d
            ./.circleci/wait-for-it.sh localhost:5432 -t 10
            sleep 10

      - run: |
          source /opt/circleci/.nvm/nvm.sh
          yarn # @todo: reuse modules from cache
          yarn test:e2e

workflows:
  version: 2

  mainflow:
    jobs:
      - test

      - test-e2e:
          requires:
            - test
